### ISSUE TITLE
Materialize bootbox callback not working

### ISSUE THREAD

**Issue by JacksonSoul** [iqbalfn/materialize-bootbox#5]
Hello, I've implemented materializecss and I searched for a library similar to bootbox for bootstrap and I found materialize-bootbox. I've been trying to use the confirm method with a callback, but the callback is not working.

I'm using css and javascript files provided from the materializecss site. (The callback is not working using those files)

I saw that materialize-bootbox is using "alpha" version, so I implemented those alpha files both for CSS and Javascript, everything worked fine with materialize-bootbox, but now I have problems with select inputs, they are not being initialized correctly it throws this error: 
**Uncaught TypeError: e.each is not a function
    at Function.value (materialize.min.js:6)
    at <anonymous>:2:34**

Any solution for this issue?
Thanks in advance.

**Comment by iqbalfn** [comment]
Please also provide the script you use to call the confirm action. That way I can try it here by my self easier me to recheck.

**Comment by JacksonSoul** [comment]
Thanks for your reply. This is the way in which I'm calling the action

First, I did it this way and the callback did not worked:
`mzbox.confirm({
  title: 'Confirmation',
  message: 'Are you sure you want to accept this request?',
  callback: function(res){
      alert(res);
  }
});`

Then I realized I'm able to add custom buttons and did it this way and also the callback not worked:
`mzbox.dialog({
                title: 'Confirmación',
                message: 'Are you sure you want to accept this request?',
                callback: function (res) {
                    alert(res);
                },
                buttons: {
                    confirm: {
                        label: 'Yes',
                        default: true
                    },
                    cancel: {
                        label: 'No'
                    }
                }
            });`

I'm attaching the scripts I'm using (.zip cause I can't attach .js files) 
[scripts.zip](https://github.com/iqbalfn/materialize-bootbox/files/5570871/scripts.zip)

mzbox provided by the https://materialize-bootbox.js.org/ site and materialize scripts (1.0.0) provided by https://materializecss.com/

I'll be waiting for your reply, Thank you.

**Comment by iqbalfn** [comment]
Thank you for the details, I get it now. This library is developed under [materialize-css 1.0.0-alpha.2](https://materialize-bootbox.js.org/#!). And the one you try is `1.0.0`. Maybe they change something that broke the event listener.

I'll get back to the update when I get home.

If you have same spare time for this, it will really help me fixing the bug.

**Comment by iqbalfn** [comment]
It's already updated to support Materialize v1.0.0. They change various config from alpha to release that broke this library. Please recheck on your side and inform it this issue can be closed.

**Comment by JacksonSoul** [comment]
Hello, it's working now. Also sorry, I don't have too much free time, before you solved the issue I did my "quick and dirty" implementation of a simple confirm dialog. But now I'll use the one you did.
Thank you 👍
